default_language_version:
  python: python3.12.3

exclude: '^(Libs/|venv/|.venv/|env/|Lib/)'

repos:
  - repo: https://github.com/pycqa/pylint
    rev: v2.13.5
    hooks:
      - id: pylint
        name: Check pylint issues
        types: [python]